import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { dir } from "i18next";

import { languages } from "../i18n/settings";
import NavBar from "@/components/ui/navbar";
import { cn } from "@/lib/utils";

import "./globals.css";
import Footer from "@/components/ui/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }));
}

interface RootLayoutProps {
  children: React.ReactNode;
  params: {
    lng: string;
  };
}

export default function RootLayout({
  children,
  params: { lng },
}: RootLayoutProps) {
  return (
    <html lang={lng} dir={dir(lng)}>
      <body
        className={cn(
          "min-h-screen flex flex-col justify-between",
          inter.className
        )}
      >
        <NavBar lng={lng} />
        {children}
        <Footer lng={lng} />
      </body>
    </html>
  );
}
